In [43]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
import kagglehub

/kaggle/input/datasets/nabeelqureshitiii/student-performance-dataset/student_performance.csv

In [44]:
df = pd.read_csv("/kaggle/input/datasets/nabeelqureshitiii/student-performance-dataset/student_performance.csv")

In [45]:
df.sample(5)

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
739403,739404,19.4,70.7,3.7,77.0,B
499498,499499,20.6,72.2,6.5,93.6,A
160581,160582,17.3,79.5,3.5,100.0,A
791675,791676,17.8,84.0,4.9,93.2,A
920654,920655,23.9,77.5,7.4,100.0,A

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 6 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   student_id               1000000 non-null  int64
 1   weekly_self_study_hours  1000000 non-null  float64
 2   attendance_percentage    1000000 non-null  float64
 3   class_participation      1000000 non-null  float64
 4   total_score              1000000 non-null  float64
 5   grade                    1000000 non-null  object
dtypes: float64(4), int64(1), object(1)
memory usage: 45.8+ MB

In [47]:
X= df[['weekly_self_study_hours','attendance_percentage','class_participation']]

In [48]:
y = df['total_score']

In [49]:
X.shape

(1000000, 3)

In [50]:
y.shape

(1000000,)

**Datset Split and processing**

In [51]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

In [52]:
X_train.sample(5)

        weekly_self_study_hours  attendance_percentage  class_participation
452895                      6.6                   82.7                  7.0
913028                     12.3                   77.5                  6.6
892913                     22.9                   82.7                  3.6
303213                      9.2                   89.4                  6.3
253126                     15.5                   95.1                  5.0

In [53]:
X_test.sample(5)

        weekly_self_study_hours  attendance_percentage  class_participation
192177                     17.1                   78.5                  5.1
132110                     10.0                   79.0                  7.3
547266                     21.8                   85.9                  8.7
64724                      22.2                   81.5                  5.9
921217                     14.8                   94.6                  6.6

In [54]:
y_train.sample(5)

513769     84.2
252106     72.0
996317     76.8
264828     82.3
59167     100.0
Name: total_score, dtype: float64

In [55]:
y_test.sample(5)

18856      73.2
736132    100.0
500769     84.2
532371     83.3
773602     92.4
Name: total_score, dtype: float64

**Now Import Model**

In [56]:
from sklearn.linear_model import LinearRegression

In [57]:
model = LinearRegression()

**Giving Training Data to model**

In [58]:
model.fit(X_train,y_train)

LinearRegression()

**Now prediction**

In [59]:
y_pred = model.predict(X_test)

In [60]:
print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)

Intercept: 56.96553026075668
Coefficients: [ 1.81661229e+00  3.16725844e-04 -2.78629799e-03]

**Now testing Accuracy**

In [61]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)

In [62]:
print("R² Score:", r2)
print("R² Percentage:", r2 * 100, "%")

R² Score: 0.6605494532437952
R² Percentage: 66.05494532437952 %

**Now Testing accuracy by given user Input**

In [67]:
study_hours = float(input("Weekly self-study hours: "))
attendance = float(input("Attendance percentage: "))
participation = float(input("Class participation: "))

new_student = np.array([[study_hours, attendance, participation]])

prediction = model.predict(new_student)

print("Predicted Total Score:", prediction[0])

Weekly self-study hours:  20
Attendance percentage:  50
Class participation:  9

Predicted Total Score: 93.28853559817

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(