In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub

/kaggle/input/datasets/rashedulislam011/cars-dataset/cars.csv

In [3]:
df =pd.read_csv('/kaggle/input/datasets/rashedulislam011/cars-dataset/cars.csv')

In [4]:
df.sample(5)

       brand  km_driven    fuel         owner  selling_price
3380   Honda     110000  Diesel   First Owner         650000
4303  Maruti      15000  Petrol   First Owner         335000
488      Kia      10000  Diesel   First Owner         643000
4285  Maruti     100000  Petrol  Second Owner          70000
5676  Maruti      70000  Petrol   First Owner         100000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   brand          8128 non-null   object
 1   km_driven      8128 non-null   int64
 2   fuel           8128 non-null   object
 3   owner          8128 non-null   object
 4   selling_price  8128 non-null   int64
dtypes: int64(2), object(3)
memory usage: 317.6+ KB

In [7]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

**OneHotEncoding using Pandas**

In [8]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

**K-1 OneHotEncoding**

In [9]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

* **OneHotEncoding using Sklearn**
* **Now train/test split**

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    df.iloc[:,0:4],
    df.iloc[:,-1],
    test_size=0.2,
    random_state=2
)

In [12]:
X_train

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner
...        ...        ...     ...           ...
3606      Ford      35000  Diesel   First Owner
5704    Maruti     120000  Petrol   First Owner
6637      Tata      15000  Petrol   First Owner
2575    Maruti      32500  Diesel  Second Owner
7336     Isuzu     121000  Diesel   First Owner

[6502 rows x 4 columns]

In [15]:
from sklearn.preprocessing import OneHotEncoder

In [18]:
ohe = OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [19]:
X_train_new = ohe.fit_transform(
    X_train[['fuel','owner']]
)

In [20]:
X_test_new = ohe.transform(X_test[['fuel','owner']])

In [21]:
X_train_new.shape

(6502, 7)

In [22]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], dtype=object)

**OneHotEncoding with Top Categories**

In [23]:
counts = df['brand'].value_counts()

In [24]:
df['brand'].nunique()
threshold = 100

In [25]:
repl = counts[counts <= threshold].index

In [26]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
4637,False,False,False,False,False,False,True,False,False,False,False,False,False
5074,False,False,False,True,False,False,False,False,False,False,False,False,False
5501,False,False,False,False,False,False,True,False,False,False,False,False,False
5657,False,False,False,False,True,False,False,False,False,False,False,False,False
3412,False,False,False,False,False,False,False,False,False,False,False,False,True